package MainApp;

public enum Error_Type {
    TAG_MISMATCH,
    FUNCTION_DUPLICATION,
    VARIABLE_DUPLICATION,
    UNDECLARED_PROPERTY,
    VAR_NOT_EXIST,
    FUNCTION_NOT_EXIST,
    INVALID_ARGUMENT_COUNT,
    RETURN_OUTSIDE_FUNCTION,
    MISSING_FLASK_VARIABLE,
    TYPE_ERROR

}
